### ISSUE TITLE
Code can't be imported, reused.

### ISSUE THREAD

**Issue by globaltrouble** [alya783/python_app#3]
Current application configure server/client during script flow. the code can't be imported.

Please consider avoiding global actions and wrap each group of actions into function.
Each function must be `clear` function and use only variables passed to its arguments, consider avoiding global variables.
Also wrap app logic into `main` function (just sequentially call your functions inside it) and `main` function itself wrap into ```__name__ == "__main__"" ``` , details about name == main [are](here https://www.freecodecamp.org/news/if-name-main-python-example/)

**Comment by alya783** [comment]
Main function has been created, no code in global namespace, added __name__ == "__main__"". https://github.com/alya783/python_app/pull/1
